builds:
  - binary: blackbeard
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/Meetic/blackbeard/pkg/version.version={{.Version}}
# archive:
#   replacements:
#     darwin: macos
#     linux: linux
#     windows: windows
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
